/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#002113",
        error: "#ffb4ab",
        "on-tertiary-fixed-variant": "#3a485c",
        "error-container": "var(--color-error-container)",
        "status-warning": "var(--color-status-warning)",
        "primary-container": "var(--color-primary-container)",
        "on-surface": "var(--color-on-surface)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        surface: "var(--color-surface)",
        "surface-container-high": "var(--color-surface-container-high)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "inverse-on-surface": "#263143",
        "on-tertiary": "#233144",
        "on-primary-fixed-variant": "#3f465c",
        "on-error": "#690005",
        tertiary: "#b9c7e0",
        "primary-fixed-dim": "#bec6e0",
        "inverse-surface": "#d8e3fb",
        "status-success": "var(--color-status-success)",
        "primary-fixed": "#dae2fd",
        "tertiary-fixed-dim": "#b9c7e0",
        primary: "var(--color-primary)",
        "on-primary-container": "#798098",
        "secondary-fixed-dim": "#4edea3",
        "tertiary-fixed": "#d5e3fd",
        "surface-bright": "#2f3a4c",
        "inverse-primary": "#565e74",
        "on-secondary-container": "#00311f",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-container": "var(--color-surface-container)",
        "surface-variant": "var(--color-surface-variant)",
        outline: "var(--color-outline)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-background": "var(--color-on-background)",
        "on-primary": "var(--color-on-primary)",
        "on-secondary-fixed-variant": "#005236",
        "status-critical": "var(--color-status-critical)",
        "surface-border": "var(--color-surface-border)",
        "data-focus": "var(--color-data-focus)",
        secondary: "var(--color-secondary)",
        "surface-tint": "#bec6e0",
        "surface-dim": "#081425",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-fixed": "#6ffbbe",
        background: "var(--color-background)",
        "tertiary-container": "#09182a",
        "on-tertiary-fixed": "#0d1c2f",
        "on-tertiary-container": "#738298",
        "secondary-container": "#00a572",
        "on-error-container": "var(--color-on-error-container)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        gutter: "16px",
        base: "4px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "data-tabular": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "data-tabular": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
