/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#002113",
        error: "#ffb4ab",
        "on-tertiary-fixed-variant": "#3a485c",
        "error-container": "#93000a",
        "status-warning": "#F59E0B",
        "primary-container": "#0f172a",
        "on-surface": "#d8e3fb",
        "on-primary-fixed": "#131b2e",
        "on-surface-variant": "#c6c6cd",
        surface: "#081425",
        "surface-container-high": "#1f2a3c",
        "outline-variant": "#45464d",
        "surface-container-lowest": "#040e1f",
        "inverse-on-surface": "#263143",
        "on-tertiary": "#233144",
        "on-primary-fixed-variant": "#3f465c",
        "on-error": "#690005",
        tertiary: "#b9c7e0",
        "primary-fixed-dim": "#bec6e0",
        "inverse-surface": "#d8e3fb",
        "status-success": "#10B981",
        "primary-fixed": "#dae2fd",
        "tertiary-fixed-dim": "#b9c7e0",
        primary: "#bec6e0",
        "on-primary-container": "#798098",
        "secondary-fixed-dim": "#4edea3",
        "tertiary-fixed": "#d5e3fd",
        "surface-bright": "#2f3a4c",
        "inverse-primary": "#565e74",
        "on-secondary-container": "#00311f",
        "surface-container-highest": "#2a3548",
        "surface-container": "#152031",
        "surface-variant": "#2a3548",
        outline: "#909097",
        "surface-container-low": "#111c2d",
        "on-background": "#d8e3fb",
        "on-primary": "#283044",
        "on-secondary-fixed-variant": "#005236",
        "status-critical": "#EF4444",
        "surface-border": "#334155",
        "data-focus": "#38BDF8",
        secondary: "#4edea3",
        "surface-tint": "#bec6e0",
        "surface-dim": "#081425",
        "on-secondary": "#003824",
        "secondary-fixed": "#6ffbbe",
        background: "#081425",
        "tertiary-container": "#09182a",
        "on-tertiary-fixed": "#0d1c2f",
        "on-tertiary-container": "#738298",
        "secondary-container": "#00a572",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        gutter: "16px",
        base: "4px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "data-tabular": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "data-tabular": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
